name: Pull Request Benchmark

on:
  pull_request:

jobs:
  bench:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{github.base_ref}}
