name: Benchmark

on:
  pull_request:

jobs:
  bench:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    steps:
      - uses: taiki-e/checkout-action@v1

      - uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{github.base_ref}}
