name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: taiki-e/checkout-action@v1

      - uses: oxc-project/setup-rust@v1.0.0
        with:
          save-cache: ${{ github.ref_name == 'main' }}

      - run: cargo check

      - run: cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1

      - uses: oxc-project/setup-rust@v1.0.0
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: clippy
          components: clippy

      - run: cargo clippy --all-targets --all-features -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1

      - uses: oxc-project/setup-rust@v1.0.0
        with:
          components: rustfmt

      - run: cargo fmt --check
